name: Build and Push Docker Image

on:
  pull_request:
    branches:
      - main

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_PASSWORD }}

      - name: Build Docker image
        run: docker build -t your-dockerhub-username/django-docker-app:latest .

      - name: Push Docker image
        run: docker push your-dockerhub-username/django-docker-app:latest

      - name: Trigger Deployment Workflow
        uses: appleboy/trigger-workflow-action@v1
        with:
          workflow-id: deploy-to-ec2
          workflow-branch: main
          token: ${{ secrets.GITHUB_TOKEN }}
