# .github/workflows/build-docker.yml
name: Build and Push Docker Image
  #on:
  #push:
  #  branches:
  #    - main
     # - dev

env:
  DOCKER_REGISTRY: docker.io
  DOCKER_IMAGE_NAME: your-username/your-django-app
  DOCKER_TAG: ${{ github.ref_name }}

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_HUB_USER }}
          password: ${{ secrets.DOCKER_HUB_PASSWORD }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v7
        with:
          context: .
          push: true
          tags: |
            $DOCKER_REGISTRY/$DOCKER_IMAGE_NAME:$DOCKER_TAG
            $DOCKER_REGISTRY/$DOCKER_IMAGE_NAME:latest
