name: Deploy to EC2

on:
  workflow_dispatch:
    inputs:
      image_tag:
        description: "Docker image tag to deploy"
        required: true
        default: latest

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: SSH into EC2
        uses: appleboy/ssh-action@v1
        with:
          host: 16.171.33.136
          username: ubuntu
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            sudo docker stop  django-mysql-app || true
            sudo docker rm -f django-mysql-app || true
            sleep 30
            sudo docker pull yaqbx/django-mysql-app:${{ inputs.image_tag }}
            sudo docker run -d -p 8000:8000 --name django-mysql-app yaqbx/django-mysql-app:${{ inputs.image_tag }}
