name: Build and push docker image!

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build-and-push:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
  #  - name: Install docker
  #    run: |
  #      sudo apt-get update
  #      sudo apt install -y docker.io

    - name: Login to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_HUB_USERNAME }}
        password: ${{ secrets.DOCKER_HUB_PASSWORD }}
    
    - name: Build Docker image and push to hub
      run: |
        TIMESTAMP=$(date +"%Y%m%d%H%M")
        docker build -t ${{ secrets.DOCKER_HUB_USERNAME }}/django-mysql-app:$TIMESTAMP .
        docker push ${{ secrets.DOCKER_HUB_USERNAME }}/django-mysql-app:$TIMESTAMP
    
    #- name: Push Docker image
    #  run: |
    #    docker push ${{ secrets.DOCKER_HUB_USERNAME }}/django-mysql-app:$TIMESTAMP

    - name: Trigger Github workflow
  # You may pin to the exact commit or the version.
  # uses: yakubique/trigger-github-workflow@5dcfcea92d62b4723e3cbad8bc1c415b654d1007
      uses: yakubique/trigger-github-workflow@v1
      with:
    # Owner/repository
          repository: yaqbx/django-docker 
    # Workflow ID or workflow's filename
          workflow: deploy_to_ec2
    # Github token
          token: ${{ secrets.TOKEN_WITH_SCOPE }}
    # Reference branch
          ref: main
    
      
